/**
 * Phase 1 — Backcompat (additive-only) contract.
 *
 * Per docs/ops/db/phase-1-production-harden.md tests section:
 *   "Apply schema.sql from v1.0.2 to a fresh DB. Then run Phase 1's migrate().
 *    Verify no error, verify schema_version row exists with current package
 *    version, verify no existing table/column/index was modified."
 *
 * Diff strategy: information_schema / pg_catalog enumeration of tables,
 * columns, indexes, check constraints, and foreign keys (the structural
 * equivalents of `pg_dump --schema-only`). Calling pg_dump in-process is
 * fragile across pg_dump versions and pollutes the runner with a binary
 * dependency that CI may not have; pg_catalog enumeration produces the
 * same information deterministically.
 *
 * Allowed additive metadata is enumerated below. Anything not in that
 * allowlist that appears in the diff is a backcompat regression.
 */

import { afterAll, beforeEach, describe, expect, it } from 'vitest';
import { migrate } from '../migration-api.js';
import {
  applyLegacySchema,
  captureStructuralSnapshot,
  useMigrationTestPool,
  type StructuralSnapshot,
} from './migration-test-helpers.js';

const pool = useMigrationTestPool({ beforeEach, afterAll });

const ALLOWED_NEW_TABLES = new Set<string>(['pgmigrations', 'schema_version']);
const ALLOWED_NEW_INDEXES = new Set([
  // schema_version primary key is auto-generated by Postgres on `applied_at`.
  'schema_version_pkey',
  // Explicit applied_at DESC index per the plan §1 (schema_version table).
  'idx_schema_version_applied_at',
]);
const ALLOWED_NEW_CHECK_CONSTRAINTS = new Set<string>();
const ALLOWED_NEW_FOREIGN_KEYS = new Set<string>();

describe('Phase 1 migrate() is additive against v1.0.2', () => {
  it('preserves every legacy table, column, index, check, and FK definition', async () => {
    await applyLegacySchema(pool);
    const before = await captureStructuralSnapshot(pool);
    await migrate({ pool });
    const after = await captureStructuralSnapshot(pool);

    assertEverythingLegacySurvives(before, after);
  });

  it('only adds migration bookkeeping metadata (no new objects on existing tables)', async () => {
    await applyLegacySchema(pool);
    const before = await captureStructuralSnapshot(pool);
    await migrate({ pool });
    const after = await captureStructuralSnapshot(pool);

    assertNewObjectsAreAllowed(before, after);
  });

  it('stamps schema_version with the current package version after migrate', async () => {
    await applyLegacySchema(pool);
    const result = await migrate({ pool });

    const { rows } = await pool.query<{ sdk_version: string; schema_sha256: string }>(
      `SELECT sdk_version, schema_sha256 FROM schema_version
        ORDER BY applied_at DESC LIMIT 1`,
    );
    expect(rows).toHaveLength(1);
    expect(rows[0].sdk_version).toBe(result.schemaVersion.sdkVersion);
    expect(rows[0].schema_sha256).toBe(result.schemaVersion.schemaSha256);
  });
});

function assertEverythingLegacySurvives(
  before: StructuralSnapshot,
  after: StructuralSnapshot,
): void {
  assertNoRemovedTables(before, after);
  assertNoRemovedColumns(before, after);
  assertColumnTypesUnchanged(before, after);
  assertNoRemovedIndexes(before, after);
  assertIndexDefinitionsUnchanged(before, after);
  assertNoRemovedCheckConstraints(before, after);
  assertNoRemovedForeignKeys(before, after);
}

function assertNewObjectsAreAllowed(
  before: StructuralSnapshot,
  after: StructuralSnapshot,
): void {
  const newTables = subtractByName(after.tables, before.tables, (t) => t.name);
  for (const table of newTables) {
    expect(ALLOWED_NEW_TABLES.has(table)).toBe(true);
  }

  const newIndexKeys = subtractByName(after.indexes, before.indexes, indexKey);
  for (const key of newIndexKeys) {
    expect(isAllowedNewIndex(key)).toBe(true);
  }

  const newCheckKeys = subtractByName(
    after.checkConstraints,
    before.checkConstraints,
    constraintKey,
  );
  for (const key of newCheckKeys) {
    expect(isAllowedNewConstraint(key, ALLOWED_NEW_CHECK_CONSTRAINTS)).toBe(true);
  }

  const newFkKeys = subtractByName(after.foreignKeys, before.foreignKeys, constraintKey);
  for (const key of newFkKeys) {
    expect(isAllowedNewConstraint(key, ALLOWED_NEW_FOREIGN_KEYS)).toBe(true);
  }
}

function indexKey(spec: { table: string; index: string }): string {
  return `${spec.table}::${spec.index}`;
}

function constraintKey(spec: { table: string; constraint: string }): string {
  return `${spec.table}::${spec.constraint}`;
}

function subtractByName<T>(
  after: ReadonlyArray<T>,
  before: ReadonlyArray<T>,
  toKey: (value: T) => string,
): string[] {
  const beforeKeys = new Set(before.map(toKey));
  return after.map(toKey).filter((key) => !beforeKeys.has(key));
}

function isAllowedNewIndex(key: string): boolean {
  const [tableName, indexName] = key.split('::');
  return ALLOWED_NEW_TABLES.has(tableName) || ALLOWED_NEW_INDEXES.has(indexName);
}

function isAllowedNewConstraint(key: string, allowedNames: ReadonlySet<string>): boolean {
  const [tableName, constraintName] = key.split('::');
  return ALLOWED_NEW_TABLES.has(tableName) || allowedNames.has(constraintName);
}

function assertNoRemovedTables(before: StructuralSnapshot, after: StructuralSnapshot): void {
  const afterNames = new Set(after.tables.map((t) => t.name));
  const removed = before.tables.map((t) => t.name).filter((name) => !afterNames.has(name));
  expect(removed).toEqual([]);
}

function assertNoRemovedColumns(before: StructuralSnapshot, after: StructuralSnapshot): void {
  const afterByTable = new Map(after.tables.map((t) => [t.name, t.columns]));
  for (const beforeTable of before.tables) {
    const afterColumns = afterByTable.get(beforeTable.name);
    if (!afterColumns) continue;
    const afterColumnNames = new Set(afterColumns.map((c) => c.column));
    for (const beforeColumn of beforeTable.columns) {
      expect(
        afterColumnNames.has(beforeColumn.column),
        `legacy column ${beforeTable.name}.${beforeColumn.column} was removed`,
      ).toBe(true);
    }
  }
}

function assertColumnTypesUnchanged(before: StructuralSnapshot, after: StructuralSnapshot): void {
  const afterByTable = new Map(
    after.tables.map((t) => [t.name, new Map(t.columns.map((c) => [c.column, c]))]),
  );
  for (const beforeTable of before.tables) {
    const afterColumns = afterByTable.get(beforeTable.name);
    if (!afterColumns) continue;
    for (const beforeColumn of beforeTable.columns) {
      const afterColumn = afterColumns.get(beforeColumn.column);
      if (!afterColumn) continue;
      expect(afterColumn.dataType).toBe(beforeColumn.dataType);
      expect(afterColumn.isNullable).toBe(beforeColumn.isNullable);
    }
  }
}

function assertNoRemovedIndexes(before: StructuralSnapshot, after: StructuralSnapshot): void {
  const afterKeys = new Set(after.indexes.map(indexKey));
  const removed = before.indexes.map(indexKey).filter((key) => !afterKeys.has(key));
  expect(removed).toEqual([]);
}

function assertIndexDefinitionsUnchanged(
  before: StructuralSnapshot,
  after: StructuralSnapshot,
): void {
  const afterByKey = new Map(after.indexes.map((idx) => [indexKey(idx), idx.definition]));
  for (const beforeIndex of before.indexes) {
    const afterDefinition = afterByKey.get(indexKey(beforeIndex));
    if (!afterDefinition) continue;
    expect(afterDefinition).toBe(beforeIndex.definition);
  }
}

function assertNoRemovedCheckConstraints(
  before: StructuralSnapshot,
  after: StructuralSnapshot,
): void {
  const afterKeys = new Set(after.checkConstraints.map(constraintKey));
  const removed = before.checkConstraints.map(constraintKey).filter((key) => !afterKeys.has(key));
  expect(removed).toEqual([]);
}

function assertNoRemovedForeignKeys(
  before: StructuralSnapshot,
  after: StructuralSnapshot,
): void {
  const afterKeys = new Set(after.foreignKeys.map(constraintKey));
  const removed = before.foreignKeys.map(constraintKey).filter((key) => !afterKeys.has(key));
  expect(removed).toEqual([]);
}
